telegram_token: <value> # Telegram token id
chatbase_token: <value> # Chatbase token for store statistic
pause_mailing: 10 # Delay between messages in mailing

# Messages for events
messages:
  start: "Hello! I can give to you top N posts by likes from Instagram account"
  help: "Just send me a link to profile"
  loading: "Your data is loading ..."
  error: "Invalid URL, username must be in link and profile must be public"

top_n: 10 # how many top posts to display
lookback_posts: 100 # Get top posts from last N posts
